version: '2'
services:
  db: 
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: ./Dockerfile.prod
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=www.uptownok.com
      - LETSENCRYPT_HOST=www.uptownok.com
      - LETSENCRYPT_EMAIL=keith@hand.technology
    depends_on:
      - db

networks:
  default:
    external:
      name: webproxy
